### ISSUE TITLE
Hero positions overlap on the chessboard

### ISSUE THREAD

**Issue by aLIEzsss4** [HelheimLabs/autochessia#177] opened 2023-09-12 18:00 UTC
![92061694541476_ pic](https://github.com/HelheimLabs/autochessia/assets/24380830/b7271b44-71b8-43cb-a6f2-da4a6cf9c9b0)

**Comment by ClaudeZsb** [comment] 2023-11-19 15:40
#192 
This might be caused by the bug fixed in this PR.

**Closed as completed** 2023-11-19 23:06 UTC
